"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var app = require("express")();
var tritonNode_1 = require("./tritonNode");
var tritonNode = new tritonNode_1.TritonNode(app);
var port = process.argv[process.argv.length - 1];
var httpServer = tritonNode.createHttpServer(app);
tritonNode.setServerPort(port);
var ops = { path: '/triton', pingInterval: 10000, pingTimeout: 5000 };
var io = require('socket.io');
var server = tritonNode.creatSocketServer(io, ops);
server.on('connect', function (data) { console.log(data); });
